services:
  consumer:
    image: my_confluent_img
    build: /docker
    container_name: consumer
    environment:
      - SASL_USERNAME=${SASL_USERNAME}
      - SASL_PASSWORD=${SASL_PASSWORD}
    volumes:
      - ./app:/home/app              
    working_dir: /home/app
    command: python test_producer02.py
