version: '3.8'

services:
  confluent-service:
    image: jedha/confluent-image
    volumes:
      - .:/home/app
    environment:
      - SASL_USERNAME=${SASL_USERNAME}
      - SASL_PASSWORD=${SASL_PASSWORD}
    # stdin_open: true
    # tty: true
    # command: python /home/app/test_producer02.py